# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lat', models.CharField(max_length=20)),
                ('Long', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IncidentID', models.CharField(max_length=100)),
                ('CallerName', models.CharField(blank=True, max_length=250)),
                ('CallerID', models.CharField(blank=True, max_length=9)),
                ('Datetime', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=250)),
                ('Title', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=1000)),
                ('Priority', models.CharField(max_length=6)),
                ('Casualty', models.IntegerField()),
                ('Vetted', models.BooleanField(default=False)),
                ('Radius', models.IntegerField()),
                ('Operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='Report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gui.Report'),
        ),
    ]
